# Generated by Django 2.2.1 on 2020-02-07 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='cdate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
